### ISSUE TITLE
Add special lore to dragon egg to include player's username, as well as modify item name

### ISSUE THREAD

**Issue by solonovamax** [Kira-NT/egg-of-capitalism#3]
Dragon egg items should have special lore including the username of who killed the dragon.

Here is a demo of the idea:

![inventory](https://user-images.githubusercontent.com/46940694/163863147-295a09ab-06b8-4548-84d3-0876ca32a918.png)

![item frame](https://user-images.githubusercontent.com/46940694/163863331-67d06481-463a-4603-b687-db4301177526.png)

The following NBT was used to create the item:

```json
{
    "display": {
        "Name": [
                {
                    "text": "solonovamax's ",
                    "italic": false
                },
                {
                    "translate": "block.minecraft.dragon_egg",
                    "italic": false
                }
        ],
        "Lore": [
            [
                {
                    "text": "Created by ",
                    "color": "gray",
                    "italic": false
                },
                {
                    "text": "solonovamax",
                    "color": "dark_purple",
                    "italic": false
                }
            ],
            [
                {
                    "text": "Dragon killed on ",
                    "color": "gray",
                    "italic": false
                },
                {
                    "text": "04/18/2022",
                    "color": "gray",
                    "italic": false
                }
            ]
        ]
    }
}
```

And you can /give yourself the item using the following command:
```
/give @p dragon_egg{ display: { Name: '[ { "text": "solonovamax\'s ", "italic": false }, { "translate": "block.minecraft.dragon_egg", "italic": "false" } ]', Lore: [ '[ { "text": "Created by ", "color": "gray", "italic": false }, { "text": "solonovamax", "color": "dark_purple", "italic": false } ]', '[ { "text": "Dragon killed on ", "color": "gray", "italic": false }, { "text": "04/18/2022", "color": "gray" } ]' ] } }
```

I'm going to attempt a PR with this change in not too long.

**Comment by solonovamax** [comment]
Actually, I'm kinda at a standstill for implementing this.

I'm not sure how to go about it. I don't particularly want to make dragon eggs a block entity (that might fuck with vanilla clients)
So, I was originally going to do it using blockstates, but it seems mc initializes a list of every possible block state at the start of the game & I don't wanna initialize the huge amount of blockstates for every single UUID in existence.

Also, it can't work with a finite list based on who's beaten the dragon already once the server starts, as that can change during runtime if someone new beats the dragon.

**Comment by Kira-NT** [comment]
You're right. It's just impossible implement the feature without completely nuking one aspect of the game or another. I want to keep this mod as simple as it is now (also it's completely server-side), but I may make something esoteric like this in other project, because it's really good idea :)
